### ISSUE TITLE
Check button on System tab shows "0 Packages are installed"

### ISSUE THREAD

**Issue by alphastar868** [eloaders/I-Nex#14]
Discovered a bug with the Check button that causes the field to show "0 Packages are installed" on non-dpkg systems (e.g. CentOS).

Modifying the Shell *grep* on line 777 of Finfosys.class to run conditionally allows the subsequent *IsNull* to be True for rpm-based systems.

Will post this patch to #13 as well.

**Comment by eloaders** [comment]
Fixed: https://github.com/eloaders/I-Nex/commit/5813d16340787a2287513f65755b3caa9599ef86
