### ISSUE TITLE
Ubuntu 16.04 and Linux Mint 18 package?

### ISSUE THREAD

**Issue by xet7** [eloaders/I-Nex#19]
Hi,
could you add xenial / Ubuntu 16.04 and Linux Mint 18 package to repository?

Compile info and discussion at:
https://bugs.launchpad.net/i-nex/+bug/1595008

**Comment by eloaders** [comment]
https://code.launchpad.net/~i-nex-development-team/+recipe/i-nex-daily

**Comment by xet7** [comment]
Thanks! :+1:
