### ISSUE TITLE
useless dependency on libXext.so.6 or so compilation claims

### ISSUE THREAD

**Issue by shirishag75** [eloaders/I-Nex#6]
Hi all, 
I was compiling I-Nex and came across the above :-

     ~/games/I-Nex$ fakeroot debian/rules binary
    dh binary  --with autoreconf
       dh_testroot
       dh_prep
       dh_auto_install
    make[1]: Entering directory '/data/shirish/Games/I-Nex'
    Create nedded dirs...
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/usr/share/applications
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/usr/share/i-nex/pastebinit
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/usr/share/i-nex/pastebinit/pastebin.d
    Install pastebinit and other...
    install -m 0755 debian/i-nex.desktop /data/shirish/Games/I-Nex/debian/i-nex/usr/share/applications/
    install -m 0755 debian/i-nex-library.desktop /data/shirish/Games/I-Nex/debian/i-nex/usr/share/applications/
    install -m 0755 pastebinit /data/shirish/Games/I-Nex/debian/i-nex/usr/share/i-nex/pastebinit/
    install -m 0755 pastebinit.xml /data/shirish/Games/I-Nex/debian/i-nex/usr/share/i-nex/pastebinit/
    install -m 0755 release.conf /data/shirish/Games/I-Nex/debian/i-nex/usr/share/i-nex/pastebinit/
    make -C pastebin.d install
    make[2]: Entering directory '/data/shirish/Games/I-Nex/pastebin.d'
    Installing Pastebinit Config files...
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/usr/share/i-nex/pastebinit/pastebin.d
    install -Dm644 susepaste.org.conf pastebin.com.conf paste.opensuse.org.conf lpaste.net.conf slexy.org.conf paste.kde.org.conf paste.pound-python.org.conf paste.pocoo.org.conf paste.ubuntu.org.cn.conf pastie.org.conf paste.ubuntu.com.conf paste.debian.net.conf dpaste.com.conf pastebin.mate-desktop.org.conf paste2.org.conf cxg.de.conf paste.openstack.org.conf yourpaste.net.conf p.defau.lt.conf paste.drizzle.org.conf hpaste.org.conf sprunge.us.conf fpaste.org.conf pb.daviey.com.conf /data/shirish/Games/I-Nex/debian/i-nex/usr/share/i-nex/pastebinit/pastebin.d/
    make[2]: Leaving directory '/data/shirish/Games/I-Nex/pastebin.d'
    Install pixmaps...
    make -C pixmaps install
    make[2]: Entering directory '/data/shirish/Games/I-Nex/pixmaps'
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/usr/share/pixmaps
    install -m 644 i-nex.png /data/shirish/Games/I-Nex/debian/i-nex/usr/share/pixmaps/
    install -m 644 i-nex-16.png /data/shirish/Games/I-Nex/debian/i-nex/usr/share/pixmaps/
    install -m 644 i-nex-32.png /data/shirish/Games/I-Nex/debian/i-nex/usr/share/pixmaps/
    install -m 644 i-nex-128.png /data/shirish/Games/I-Nex/debian/i-nex/usr/share/pixmaps/
    make[2]: Leaving directory '/data/shirish/Games/I-Nex/pixmaps'
    Install changelogs...
    make -C changelogs install
    make[2]: Entering directory '/data/shirish/Games/I-Nex/changelogs'
    Installing Changelogs...
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex
    install -Dm644 changelog-0.5.0 changelog-7.2.1 changelog-0.4.6 changelog-0.6.4 changelog-7.4.0 changelog-0.4.8 changelog-0.5.8 changelog-0.5.6 changelog-0.4.8.1 changelog-0.6.2 changelog-7.2.0 changelog-7.0.0 changelog-0.6.0 changelog-0.5.4 changelog-0.5.1 changelog-0.6.6 changelog-0.5.2 /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex
    Compress Changelogs...
    gzip -9 /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/changelog-0.4.6
    gzip -9 /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/changelog-0.4.8
    gzip -9 /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/changelog-0.4.8.1
    gzip -9 /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/changelog-0.5.0
    gzip -9 /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/changelog-0.5.1
    gzip -9 /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/changelog-0.5.2
    gzip -9 /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/changelog-0.5.4
    gzip -9 /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/changelog-0.5.6
    gzip -9 /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/changelog-0.5.8
    gzip -9 /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/changelog-0.6.0
    gzip -9 /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/changelog-0.6.2
    gzip -9 /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/changelog-0.6.4
    gzip -9 /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/changelog-0.6.6
    gzip -9 /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/changelog-7.0.0
    gzip -9 /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/changelog-7.2.0
    gzip -9 /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/changelog-7.2.1
    gzip -9 /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/changelog-7.4.0
    make[2]: Leaving directory '/data/shirish/Games/I-Nex/changelogs'
    Install manpages...
    make -C manpages install
    make[2]: Entering directory '/data/shirish/Games/I-Nex/manpages'
    Installing Man pages 1...
    mkdir -p "/data/shirish/Games/I-Nex/debian/i-nex/usr/share/man/man1/"
    install -Dm644 i-nex-cpuid.1 i-nex-usage.1 i-nex.1 i-nex-edid.1 i-nex-lspci.1 i-nex.gambas.1 i-nex-cpusage.1 "/data/shirish/Games/I-Nex/debian/i-nex/usr/share/man/man1/"
    Compress Man pages 1...
    gzip -9 "/data/shirish/Games/I-Nex/debian/i-nex/usr/share/man/man1/i-nex-cpuid.1"
    gzip -9 "/data/shirish/Games/I-Nex/debian/i-nex/usr/share/man/man1/i-nex-cpusage.1"
    gzip -9 "/data/shirish/Games/I-Nex/debian/i-nex/usr/share/man/man1/i-nex-edid.1"
    gzip -9 "/data/shirish/Games/I-Nex/debian/i-nex/usr/share/man/man1/i-nex-lspci.1"
    gzip -9 "/data/shirish/Games/I-Nex/debian/i-nex/usr/share/man/man1/i-nex-usage.1"
    gzip -9 "/data/shirish/Games/I-Nex/debian/i-nex/usr/share/man/man1/i-nex.1"
    gzip -9 "/data/shirish/Games/I-Nex/debian/i-nex/usr/share/man/man1/i-nex.gambas.1"
    make[2]: Leaving directory '/data/shirish/Games/I-Nex/manpages'
    Install docs...
    make -C docs install
    make[2]: Entering directory '/data/shirish/Games/I-Nex/docs'
    Create directory...
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex
    Installing Docs copyright...
    install -Dm644 copyright "/data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/copyright"
    Create directory...
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex
    Installing Docs I-Nex.LICENSE...
    install -Dm644 I-Nex.LICENSE "/data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/I-Nex.LICENSE"
    Create directory...
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex
    Installing Docs Pastebinit.LICENSE...
    install -Dm644 Pastebinit.LICENSE "/data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/Pastebinit.LICENSE"
    Compress Docs copyright...
    gzip -9 "/data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/copyright"
    Compress Docs I-Nex.LICENSE...
    gzip -9 "/data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/I-Nex.LICENSE"
    Compress Docs Pastebinit.LICENSE...
    gzip -9 "/data/shirish/Games/I-Nex/debian/i-nex/usr/share/doc/i-nex/Pastebinit.LICENSE"
    make[2]: Leaving directory '/data/shirish/Games/I-Nex/docs'
    Install JSON...
    make -C JSON install
    make[2]: Entering directory '/data/shirish/Games/I-Nex/JSON'
    chmod +x i-nex-edid
    chmod +x i-nex-cpuid
    chmod +x i-nex-usage
    chmod +x i-nex-cpusage
    chmod +x i-nex-glinfo
    chmod +x i-nex-uname
    test -d /data/shirish/Games/I-Nex/debian/i-nex/usr/bin || mkdir /data/shirish/Games/I-Nex/debian/i-nex/usr/bin
    install -m 0755 i-nex-edid /data/shirish/Games/I-Nex/debian/i-nex/usr/bin
    test -d /data/shirish/Games/I-Nex/debian/i-nex/usr/bin || mkdir /data/shirish/Games/I-Nex/debian/i-nex/usr/bin
    install -m 0755 i-nex-cpuid /data/shirish/Games/I-Nex/debian/i-nex/usr/bin
    test -d /data/shirish/Games/I-Nex/debian/i-nex/usr/bin || mkdir /data/shirish/Games/I-Nex/debian/i-nex/usr/bin
    install -m 0755 i-nex-usage /data/shirish/Games/I-Nex/debian/i-nex/usr/bin
    test -d /data/shirish/Games/I-Nex/debian/i-nex/usr/bin || mkdir /data/shirish/Games/I-Nex/debian/i-nex/usr/bin
    install -m 0755 i-nex-cpusage /data/shirish/Games/I-Nex/debian/i-nex/usr/bin
    test -d /data/shirish/Games/I-Nex/debian/i-nex/usr/bin || mkdir /data/shirish/Games/I-Nex/debian/i-nex/usr/bin
    install -m 0755 i-nex-glinfo /data/shirish/Games/I-Nex/debian/i-nex/usr/bin
    test -d /data/shirish/Games/I-Nex/debian/i-nex/usr/bin || mkdir /data/shirish/Games/I-Nex/debian/i-nex/usr/bin
    install -m 0755 i-nex-uname /data/shirish/Games/I-Nex/debian/i-nex/usr/bin
    test -d /data/shirish/Games/I-Nex/debian/i-nex/usr/bin || mkdir /data/shirish/Games/I-Nex/debian/i-nex/usr/bin
    install -m 0755 i-nex-dimms /data/shirish/Games/I-Nex/debian/i-nex/usr/bin
    make[2]: Leaving directory '/data/shirish/Games/I-Nex/JSON'
    Install I-Nex...
    make -C I-Nex install
    make[2]: Entering directory '/data/shirish/Games/I-Nex/I-Nex'
    make[3]: Entering directory '/data/shirish/Games/I-Nex/I-Nex'
    Installing i-nex.gambas file in /usr/bin...
    make[3]: Nothing to be done for 'install-data-am'.
    make[3]: Leaving directory '/data/shirish/Games/I-Nex/I-Nex'
    make[2]: Leaving directory '/data/shirish/Games/I-Nex/I-Nex'
    Install Scripts...
    make -C Scripts install
    make[2]: Entering directory '/data/shirish/Games/I-Nex/Scripts'
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/usr/bin
    chmod +x i-nex-lspci
    install -m 0755 i-nex-lspci /data/shirish/Games/I-Nex/debian/i-nex/usr/bin
    make[2]: Leaving directory '/data/shirish/Games/I-Nex/Scripts'
    install -Dm 600 i2c_smbus.rules /data/shirish/Games/I-Nex/debian/i-nex/etc/udev/rules.d/i2c_smbus.rules
    ln -s /usr/bin/i-nex.gambas /data/shirish/Games/I-Nex/debian/i-nex/usr/bin/i-nex
    Install database files...
    make -C Database install
    make[2]: Entering directory '/data/shirish/Games/I-Nex/Database'
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/etc/i-nex
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/etc/i-nex/Database
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/etc/i-nex/Database/Logos
    install -m 0755 ../Database/Logos/216.gif ../Database/Logos/116.gif ../Database/Logos/169.gif ../Database/Logos/245.gif ../Database/Logos/177.gif ../Database/Logos/159.gif ../Database/Logos/288.gif ../Database/Logos/121.gif ../Database/Logos/1.gif ../Database/Logos/110.gif ../Database/Logos/297.gif ../Database/Logos/33.gif ../Database/Logos/310.gif ../Database/Logos/107.gif ../Database/Logos/14.gif ../Database/Logos/36.gif ../Database/Logos/301.gif ../Database/Logos/97.gif ../Database/Logos/271.gif ../Database/Logos/145.gif ../Database/Logos/249.gif ../Database/Logos/70.gif ../Database/Logos/122.gif ../Database/Logos/299.gif ../Database/Logos/82.gif ../Database/Logos/199.gif ../Database/Logos/13.gif ../Database/Logos/56.gif ../Database/Logos/22.gif ../Database/Logos/163.gif ../Database/Logos/18.gif ../Database/Logos/115.gif ../Database/Logos/30.gif ../Database/Logos/37.gif ../Database/Logos/273.gif ../Database/Logos/72.gif ../Database/Logos/21.gif ../Database/Logos/46.gif ../Database/Logos/158.gif ../Database/Logos/309.gif ../Database/Logos/11.gif ../Database/Logos/160.gif ../Database/Logos/247.gif ../Database/Logos/24.gif ../Database/Logos/57.gif ../Database/Logos/114.gif ../Database/Logos/154.gif ../Database/Logos/71.gif ../Database/Logos/61.gif ../Database/Logos/84.gif ../Database/Logos/41.gif ../Database/Logos/287.gif ../Database/Logos/190.gif ../Database/Logos/218.gif ../Database/Logos/300.gif ../Database/Logos/118.gif ../Database/Logos/100.gif ../Database/Logos/64.gif ../Database/Logos/4.gif ../Database/Logos/292.gif ../Database/Logos/9.gif ../Database/Logos/172.gif ../Database/Logos/129.gif ../Database/Logos/306.gif ../Database/Logos/233.gif ../Database/Logos/27.gif ../Database/Logos/124.gif ../Database/Logos/243.gif ../Database/Logos/235.gif ../Database/Logos/290.gif ../Database/Logos/80.gif ../Database/Logos/270.gif ../Database/Logos/60.gif ../Database/Logos/67.gif ../Database/Logos/40.gif ../Database/Logos/308.gif ../Database/Logos/206.gif ../Database/Logos/105.gif ../Database/Logos/263.gif ../Database/Logos/183.gif ../Database/Logos/224.gif ../Database/Logos/178.gif ../Database/Logos/139.gif ../Database/Logos/312.gif ../Database/Logos/293.gif ../Database/Logos/26.gif ../Database/Logos/99.gif ../Database/Logos/112.gif ../Database/Logos/186.gif ../Database/Logos/147.gif ../Database/Logos/79.gif ../Database/Logos/269.gif ../Database/Logos/246.gif ../Database/Logos/59.gif ../Database/Logos/15.gif ../Database/Logos/96.gif ../Database/Logos/39.gif ../Database/Logos/23.gif ../Database/Logos/29.gif ../Database/Logos/162.gif ../Database/Logos/19.gif ../Database/Logos/217.gif ../Database/Logos/180.gif ../Database/Logos/265.gif ../Database/Logos/125.gif ../Database/Logos/47.gif ../Database/Logos/298.gif ../Database/Logos/237.gif ../Database/Logos/221.gif ../Database/Logos/244.gif ../Database/Logos/113.gif ../Database/Logos/225.gif ../Database/Logos/8.gif ../Database/Logos/108.gif ../Database/Logos/128.gif ../Database/Logos/274.gif ../Database/Logos/241.gif ../Database/Logos/268.gif ../Database/Logos/188.gif ../Database/Logos/223.gif ../Database/Logos/25.gif ../Database/Logos/291.gif ../Database/Logos/191.gif ../Database/Logos/220.gif ../Database/Logos/294.gif ../Database/Logos/120.gif ../Database/Logos/234.gif ../Database/Logos/55.gif ../Database/Logos/302.gif ../Database/Logos/102.gif ../Database/Logos/242.gif ../Database/Logos/12.gif ../Database/Logos/171.gif ../Database/Logos/31.gif ../Database/Logos/261.gif ../Database/Logos/182.gif ../Database/Logos/248.gif ../Database/Logos/135.gif ../Database/Logos/283.gif ../Database/Logos/138.gif ../Database/Logos/185.gif ../Database/Logos/192.gif ../Database/Logos/117.gif ../Database/Logos/275.gif ../Database/Logos/266.gif ../Database/Logos/50.gif ../Database/Logos/77.gif ../Database/Logos/272.gif ../Database/Logos/119.gif ../Database/Logos/304.gif ../Database/Logos/296.gif ../Database/Logos/62.gif ../Database/Logos/196.gif ../Database/Logos/104.gif ../Database/Logos/34.gif ../Database/Logos/7.gif ../Database/Logos/276.gif ../Database/Logos/42.gif ../Database/Logos/305.gif ../Database/Logos/20.gif ../Database/Logos/32.gif ../Database/Logos/133.gif ../Database/Logos/66.gif ../Database/Logos/193.gif ../Database/Logos/45.gif ../Database/Logos/211.gif ../Database/Logos/181.gif ../Database/Logos/111.gif ../Database/Logos/166.gif ../Database/Logos/137.gif ../Database/Logos/267.gif ../Database/Logos/127.gif ../Database/Logos/109.gif ../Database/Logos/174.gif ../Database/Logos/101.gif ../Database/Logos/134.gif ../Database/Logos/170.gif ../Database/Logos/126.gif ../Database/Logos/83.gif ../Database/Logos/175.gif ../Database/Logos/303.gif ../Database/Logos/203.gif ../Database/Logos/103.gif ../Database/Logos/63.gif ../Database/Logos/201.gif ../Database/Logos/98.gif ../Database/Logos/78.gif ../Database/Logos/257.gif ../Database/Logos/48.gif ../Database/Logos/6.gif ../Database/Logos/38.gif ../Database/Logos/184.gif ../Database/Logos/295.gif ../Database/Logos/262.gif ../Database/Logos/289.gif ../Database/Logos/68.gif ../Database/Logos/189.gif ../Database/Logos/123.gif ../Database/Logos/65.gif ../Database/Logos/81.gif ../Database/Logos/43.gif ../Database/Logos/176.gif ../Database/Logos/136.gif ../Database/Logos/35.gif ../Database/Logos/311.gif ../Database/Logos/140.gif ../Database/Logos/28.gif ../Database/Logos/16.gif /data/shirish/Games/I-Nex/debian/i-nex/etc/i-nex/Database/Logos/
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/etc/i-nex
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/etc/i-nex/Database
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/etc/i-nex/Database/Distlogos
    install -m 0755 ../Database/Distlogos/debian.png ../Database/Distlogos/elementaryos.png ../Database/Distlogos/mint.png ../Database/Distlogos/slax.png ../Database/Distlogos/kubuntu.png ../Database/Distlogos/linux_mint_LMDE_Big_sticker.png ../Database/Distlogos/opensuse.png ../Database/Distlogos/LinuxDeepin.png ../Database/Distlogos/gentoo.png ../Database/Distlogos/netrunner.png ../Database/Distlogos/manjaro.png ../Database/Distlogos/fedora.png ../Database/Distlogos/sabayon.png ../Database/Distlogos/archlinux.png ../Database/Distlogos/linux_mint_Fluxbox_BIG_sticker.png ../Database/Distlogos/slackware.png ../Database/Distlogos/linux_mint_XFCE_Big_sticker.png ../Database/Distlogos/linux_mint_LXDE_BIG_sticker.png ../Database/Distlogos/xubuntu.png ../Database/Distlogos/linux_mint_KDE_BIG_sticker.png ../Database/Distlogos/mandriva.png ../Database/Distlogos/ubuntu.png ../Database/Distlogos/redhat.png /data/shirish/Games/I-Nex/debian/i-nex/etc/i-nex/Database/Distlogos/
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/etc/i-nex
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/etc/i-nex/Database
    install -m 0755 ../Database/intel_Core_2_Duo.json ../Database/A6.json ../Database/i5.json ../Database/atom.json ../Database/i7.json ../Database/Xeon.json ../Database/Opteron.json ../Database/intel.json ../Database/amd.json ../Database/i3.json ../Database/NULLD.json /data/shirish/Games/I-Nex/debian/i-nex/etc/i-nex/Database/
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/etc/i-nex
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/etc/i-nex/Database
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/etc/i-nex/Database/i2c
    install -m 0755 ../Database/i2c/devices.json /data/shirish/Games/I-Nex/debian/i-nex/etc/i-nex/Database/i2c/
    make[2]: Leaving directory '/data/shirish/Games/I-Nex/Database'
    Install SIV files...
    make -C SIV install
    make[2]: Entering directory '/data/shirish/Games/I-Nex/SIV'
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/etc/i-nex
    mkdir -p /data/shirish/Games/I-Nex/debian/i-nex/etc/i-nex/SIV
    install -m 0755 ../SIV/usbdevs.txt ../SIV/pcidevs.txt ../SIV/pnpdevs.txt ../SIV/mondevs.txt ../SIV/pcmdevs.txt /data/shirish/Games/I-Nex/debian/i-nex/etc/i-nex/SIV/
    make[2]: Leaving directory '/data/shirish/Games/I-Nex/SIV'
    make[1]: Leaving directory '/data/shirish/Games/I-Nex'
       dh_installdocs
       dh_installchangelogs
       dh_installman
       debian/rules override_dh_pysupport
    make[1]: Entering directory '/data/shirish/Games/I-Nex'
    dh_python2
    W: dh_python2:479: Please add dh-python package to Build-Depends
    make[1]: Leaving directory '/data/shirish/Games/I-Nex'
       dh_perl
       dh_link
       dh_compress
       debian/rules override_dh_fixperms
    make[1]: Entering directory '/data/shirish/Games/I-Nex'
    dh_fixperms
    make[1]: Leaving directory '/data/shirish/Games/I-Nex'
       dh_strip
       dh_makeshlibs
       dh_shlibdeps
    dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/i-nex/usr/bin/i-nex-glinfo was not linked against libXext.so.6 (it uses none of the library's symbols)
       dh_installdeb
       dh_gencontrol
    dpkg-gencontrol: warning: Depends field of package i-nex: unknown substitution variable ${python:Depends}
    dpkg-gencontrol: warning: package i-nex: unused substitution variable ${perl:Depends}
       dh_md5sums
       debian/rules override_dh_builddeb
    make[1]: Entering directory '/data/shirish/Games/I-Nex'
    dh_builddeb -- -z9 -Zxz
    dpkg-deb: building package `i-nex' in `../i-nex_7.4.0_amd64.deb'.
    make[1]: Leaving directory '/data/shirish/Games/I-Nex'

If you go back around 10-11 sentences from bottom you can see the info. about the useless dependency that the compilation claims.

**Comment by eloaders** [comment]
fixed?

**Comment by shirishag75** [comment]
yup, fixed.
