### ISSUE TITLE
Potrzebna pomoc przy kompilacji

### ISSUE THREAD

**Issue by tele1** [eloaders/I-Nex#9]
> Testowano na:
> openSUSE Question:243542
> Fedora 20
Ale jak to tam skompilowano ?
W /I-Nex-master/I-Nex/INSTALL pisze cos o
~~~~
./configure && make && make install
~~~~
ale w README tego nie widze , widze za to pliki make które nie wiem za bardzo jak ruszyć
> główny katalog
~~~~
$ make
Build I-Nex...
make -C I-Nex
make[1]: Entering directory '/home/gg/Downloads/test/I-Nex-master/I-Nex'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/home/gg/Downloads/test/I-Nex-master/I-Nex'
Makefile:19: recipe for target 'build-inex' failed
make: *** [build-inex] Error 2
~~~~
katalog I-nex
~~~~
$ ./configure
bash: ./configure: No such file or directory
$ make
make: *** No targets specified and no makefile found.  Stop
~~~~

Odnośnie forum z README
~~~~
Server not found
~~~~

**Comment by FadeMind** [comment]
FYI https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=i-nex-git

**Comment by tele1** [comment]
Lepiej późno niż wcale.
Czyli 

 Wchodzimy do  ... /I-Nex-master/

`sed -i 's|python3$|python2|' pastebinit`

`sed -i -e 's|^STATIC.*|STATIC = false|' i-nex.mk`

`sed -i -e 's|^UDEV_RULES_DIR.*|UDEV_RULES_DIR = /usr/lib/udev/rules.d|' i-nex.mk`

Wchodzimy do ...  /I-Nex-master/I-Nex/  lub  wykonujemy  "  cd  I-Nex  "

`autoreconf -i`

`./configure --prefix=/scieżka_instalacji

`cd ..`

`make`

 make install DESTDIR="ścieżka_instalacji"

____________________
 
W zależności gdzie instalujemy może być przy make install potrzebny root.

A może poradnik do README bys dodał ?
i ewentualne info że jest przykładowe czy coś.
